In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
pd.set_option('display.max_columns',None)

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 653721 entries, 0 to 653720
Data columns (total 56 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_x                      653721 non-null  object
 1   car_rel_url_x             653721 non-null  object
 2   datetime_scrape           653721 non-null  object
 3   name                      653721 non-null  object
 4   price_x                   653721 non-null  float64
 5   currency_x                653721 non-null  object
 6   datetime_product          653721 non-null  object
 7   city                      653721 non-null  object
 8   day                       653721 non-null  object
 9   hour                      653721 non-null  object
 10  attributes                653721 non-null  object
 11  production_year           653721 non-null  int64
 12  engine_displacement_num   653721 non-null  float64
 13  engine_displacement_unit  647933 non-null  object
 14  kilometrage_num           653721 non-null  int64
 15  kilometrage_unit          647933 non-null  object
 16  barter                    225553 non-null  object
 17  loan                      163340 non-null  object
 18  salon                     193339 non-null  object
 19  spare_parts               1762 non-null    object
 20  vip                       288941 non-null  object
 21  featured                  163835 non-null  object
 22  img_url                   653721 non-null  object
 23  id_y                      653721 non-null  object
 24  cars_id                   653721 non-null  object
 25  car_rel_url_y             653721 non-null  object
 26  datetime                  653721 non-null  object
 27  description               638192 non-null  object
 28  price_y                   653721 non-null  float64
 29  currency_y                653721 non-null  object
 30  owner_name                453496 non-null  object
 31  shop_name                 199960 non-null  object
 32  phone                     653456 non-null  float64
 33  updated                   653721 non-null  object
 34  views                     653721 non-null  int64
 35  vin                       44271 non-null   object
 36  car_details_id_x          653721 non-null  object
 37  Ban növü                  653721 non-null  object
 38  Buraxılış ili             653721 non-null  int64
 39  Hansı bazar üçün yığılıb  464216 non-null  object
 40  Marka                     653721 non-null  object
 41  Model                     653720 non-null  object
 42  Mühərrik                  653721 non-null  object
 43  Qəzalı                    1761 non-null    object
 44  Rəng                      653721 non-null  object
 45  Sahiblər                  432100 non-null  object
 46  Sürətlər qutusu           653721 non-null  object
 47  Vəziyyəti                 653718 non-null  object
 48  Yeni                      653721 non-null  object
 49  Yerlərin sayı             487890 non-null  object
 50  Yürüş                     653721 non-null  object
 51  Ötürücü                   653721 non-null  object
 52  Şəhər                     653721 non-null  object
 53  car_details_id_y          653721 non-null  object
 54  car_rel_url               653721 non-null  object
 55  extra_info                653721 non-null  object
dtypes: float64(4), int64(4), object(48)
memory usage: 279.3+ MB

## Duplicate datalarin ve Lazimsiz ve ya Tekrarlanan sutunlarin silinmesi

In [4]:
df.drop_duplicates(subset = 'car_rel_url_x',inplace = True)

In [5]:
df.drop_duplicates(subset = 'id_x', inplace = True)

In [6]:
df.drop_duplicates(subset = 'car_rel_url',inplace = True)

In [7]:
df.drop(columns = ['price_y','currency_y','car_details_id_y','id_y','car_rel_url','description','extra_info', 'Buraxılış ili','spare_parts','phone','engine_displacement_unit','kilometrage_unit','datetime_scrape', 'owner_name','shop_name','vin','datetime','updated','id_x'], inplace = True)

## Feature Engineering, Null deyerlerin doldurulmasi

In [8]:
df['datetime_product'] = df['datetime_product'].str.extract(r'(\d{2}:\d{2})')
df['datetime_product'].unique()
df['datetime_product'] = pd.to_datetime(df['datetime_product'], format = '%H:%M')

In [9]:
df.rename(columns={'day': 'tarix'}, inplace=True)

In [10]:
df['tarix'] = pd.to_datetime(df['tarix'])
df['year'] = df['tarix'].dt.year
df['month'] = df['tarix'].dt.month
df['day'] = df['tarix'].dt.day

C:\Users\Macidli\AppData\Local\Temp\ipykernel_25920\2524271643.py:1: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['tarix'] = pd.to_datetime(df['tarix'])

In [11]:
df['mühərrik həcmi'] = df['attributes'].str.extract(r'(\d+\.\d+)\s*L')
df['mühərrik həcmi'] = df['mühərrik həcmi'].astype(float)

In [12]:
df['mühərrik həcmi'] = df['mühərrik həcmi'].fillna(df['mühərrik həcmi'].median())

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154030 entries, 0 to 653719
Data columns (total 41 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   car_rel_url_x             154030 non-null  object
 1   name                      154030 non-null  object
 2   price_x                   154030 non-null  float64
 3   currency_x                154030 non-null  object
 4   datetime_product          154030 non-null  datetime64[ns]
 5   city                      154030 non-null  object
 6   tarix                     154030 non-null  datetime64[ns]
 7   hour                      154030 non-null  object
 8   attributes                154030 non-null  object
 9   production_year           154030 non-null  int64
 10  engine_displacement_num   154030 non-null  float64
 11  kilometrage_num           154030 non-null  int64
 12  barter                    35192 non-null   object
 13  loan                      22637 non-null   object
 14  salon                     15103 non-null   object
 15  vip                       17250 non-null   object
 16  featured                  8824 non-null    object
 17  img_url                   154030 non-null  object
 18  cars_id                   154030 non-null  object
 19  car_rel_url_y             154030 non-null  object
 20  views                     154030 non-null  int64
 21  car_details_id_x          154030 non-null  object
 22  Ban növü                  154030 non-null  object
 23  Hansı bazar üçün yığılıb  109849 non-null  object
 24  Marka                     154030 non-null  object
 25  Model                     154029 non-null  object
 26  Mühərrik                  154030 non-null  object
 27  Qəzalı                    1075 non-null    object
 28  Rəng                      154030 non-null  object
 29  Sahiblər                  105148 non-null  object
 30  Sürətlər qutusu           154030 non-null  object
 31  Vəziyyəti                 154027 non-null  object
 32  Yeni                      154030 non-null  object
 33  Yerlərin sayı             116044 non-null  object
 34  Yürüş                     154030 non-null  object
 35  Ötürücü                   154030 non-null  object
 36  Şəhər                     154030 non-null  object
 37  year                      154030 non-null  int32
 38  month                     154030 non-null  int32
 39  day                       154030 non-null  int32
 40  mühərrik həcmi            154030 non-null  float64
dtypes: datetime64[ns](2), float64(3), int32(3), int64(3), object(30)
memory usage: 47.6+ MB

In [14]:
df.head()

,car_rel_url_x,name,price_x,currency_x,datetime_product,city,tarix,hour,attributes,production_year,engine_displacement_num,kilometrage_num,barter,loan,salon,vip,featured,img_url,cars_id,car_rel_url_y,views,car_details_id_x,Ban növü,Hansı bazar üçün yığılıb,Marka,Model,Mühərrik,Qəzalı,Rəng,Sahiblər,Sürətlər qutusu,Vəziyyəti,Yeni,Yerlərin sayı,Yürüş,Ötürücü,Şəhər,year,month,day,mühərrik həcmi
0,/autos/8748840-hyundai-i30,Hyundai i30,15000.0,AZN,1900-01-01 23:28:00,bakı,2024-09-13,23:28,"2008, 1.6 L, 270 000 km",2008,1.6,270000,NaN,NaN,NaN,NaN,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,3c234145-d57a-4ad6-9448-d43810fc3392,/autos/8748840-hyundai-i30,492,8d84d800-fafd-4d5c-b640-f47bd6c5ac20,"Hetçbek, 5 qapı",NaN,Hyundai,i30,1.6 L/115 a.g./Dizel,NaN,Gümüşü,2,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,270 000 km,Ön,Bakı,2024,9,13,1.6
1,/autos/8475807-lada-vaz-niva-travel,LADA (VAZ) Niva Travel,23700.0,AZN,1900-01-01 23:59:00,bakı,2024-09-13,23:59,"2024, 1.7 L, 0 km",2024,1.7,0,NaN,NaN,Salon,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,c74ea36f-6be1-4de4-926d-e117197dcf00,/autos/8475807-lada-vaz-niva-travel,60189,2cf8b84b-adaf-467a-8f06-3dabcf866c8a,"Offroader / SUV, 5 qapı",Rəsmi diler,LADA (VAZ),Niva Travel,1.7 L/80 a.g./Benzin,NaN,Yaşıl,NaN,Mexaniki,"Vuruğu yoxdur, rənglənməyib",Bəli,5,0 km,Tam,Bakı,2024,9,13,1.7
2,/autos/8739686-toyota-land-cruiser,Toyota Land Cruiser,35600.0,$,1900-01-01 23:59:00,bakı,2024-09-13,23:59,"2011, 4.0 L, 164 750 km",2011,4.0,164750,NaN,NaN,NaN,vipped-icon,featured-icon,https://turbo.azstatic.com/uploads/f460x343/20...,9cefceb0-024d-4581-a869-a3c2c68a9f95,/autos/8739686-toyota-land-cruiser,2473,22bb3704-ebe7-4357-ba2f-1806d1a7042b,"Offroader / SUV, 5 qapı",Rəsmi diler,Toyota,Land Cruiser,4.0 L/282 a.g./Benzin,NaN,Ağ,0,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,8+,164 750 km,Tam,Bakı,2024,9,13,4.0
3,/autos/8712597-hyundai-elantra,Hyundai Elantra,26700.0,AZN,1900-01-01 23:59:00,bakı,2024-09-13,23:59,"2018, 2.0 L, 126 000 km",2018,2.0,126000,NaN,NaN,NaN,vipped-icon,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,459cc337-fb63-48de-9694-41554923d311,/autos/8712597-hyundai-elantra,3727,e0d16dac-4091-4417-916e-cadeff600f95,Sedan,NaN,Hyundai,Elantra,2.0 L/150 a.g./Benzin,NaN,Boz,1,Avtomat,"Vuruğu yoxdur, rənglənməyib",Xeyr,NaN,126 000 km,Ön,Bakı,2024,9,13,2.0
4,/autos/8674773-toyota-prius,Toyota Prius,10500.0,AZN,1900-01-01 23:59:00,bakı,2024-09-13,23:59,"2007, 1.5 L, 354 000 km",2007,1.5,354000,NaN,NaN,NaN,vipped-icon,NaN,https://turbo.azstatic.com/uploads/f460x343/20...,6c5ee8d8-1c6f-4fad-a694-957a4c43c25d,/autos/8674773-toyota-prius,446,82078856-0d07-4a0d-8123-69c2e5002e07,Liftbek,Amerika,Toyota,Prius,1.5 L/76 a.g./Hibrid,NaN,Qırmızı,2,Variator,"Vuruğu yoxdur, rənglənməyib",Xeyr,5,354 000 km,Ön,Bakı,2024,9,13,1.5

In [15]:
df['Yürüş'] = df['Yürüş'].str.replace('km','').str.replace(" ",'')
df['Yürüş'] = df['Yürüş'].astype(int)

In [16]:
df['Yerlərin sayı'] = df['Yerlərin sayı'].str.replace("+","")
df['Yerlərin sayı'] = df['Yerlərin sayı'].astype(float)
df['Yerlərin sayı'] = df['Yerlərin sayı'].fillna(df['Yerlərin sayı'].median())
df['Yerlərin sayı'] = df['Yerlərin sayı'].astype(int)

In [17]:
df["vip"].unique()

array([nan, 'vipped-icon'], dtype=object)

In [18]:
df["vip"] = df['vip'].fillna('not vipped-icon')

In [19]:
df['salon'] = df['salon'].fillna('No')
df['barter'] = df['barter'].fillna('Mümkün deyil')
df['loan'] = df['loan'].fillna('Kreditdə deyil')

In [20]:
df['Sahiblər'] = df['Sahiblər'].fillna(df['Sahiblər'].mode()[0])

In [21]:
df['Hansı bazar üçün yığılıb'] = df['Hansı bazar üçün yığılıb'].fillna(df['Hansı bazar üçün yığılıb'].mode()[0])

In [22]:
df['featured'] = df['featured'].fillna('No featured-icon')
df['Vəziyyəti'] = df['Vəziyyəti'].fillna('Vuruğu yoxdur, rənglənməyib')

In [23]:
df['Model'].fillna(df['Model'].mode()[0],inplace = True)

C:\Users\Macidli\AppData\Local\Temp\ipykernel_25920\1729771092.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Model'].fillna(df['Model'].mode()[0],inplace = True)

In [24]:
df['Yanacaq növü'] = df['Mühərrik'].str.extract(r'/([A-Za-zƏəİiIıÖöĞğÜüÇçŞş]+)$')
df['Yanacaq növü'].fillna(df["Yanacaq növü"].mode()[0],inplace = True)
df['Qəzalı'] = df['Qəzalı'].fillna('Xeyr')

C:\Users\Macidli\AppData\Local\Temp\ipykernel_25920\3049838774.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Yanacaq növü'].fillna(df["Yanacaq növü"].mode()[0],inplace = True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 154030 entries, 0 to 653719
Data columns (total 42 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   car_rel_url_x             154030 non-null  object
 1   name                      154030 non-null  object
 2   price_x                   154030 non-null  float64
 3   currency_x                154030 non-null  object
 4   datetime_product          154030 non-null  datetime64[ns]
 5   city                      154030 non-null  object
 6   tarix                     154030 non-null  datetime64[ns]
 7   hour                      154030 non-null  object
 8   attributes                154030 non-null  object
 9   production_year           154030 non-null  int64
 10  engine_displacement_num   154030 non-null  float64
 11  kilometrage_num           154030 non-null  int64
 12  barter                    154030 non-null  object
 13  loan                      154030 non-null  object
 14  salon                     154030 non-null  object
 15  vip                       154030 non-null  object
 16  featured                  154030 non-null  object
 17  img_url                   154030 non-null  object
 18  cars_id                   154030 non-null  object
 19  car_rel_url_y             154030 non-null  object
 20  views                     154030 non-null  int64
 21  car_details_id_x          154030 non-null  object
 22  Ban növü                  154030 non-null  object
 23  Hansı bazar üçün yığılıb  154030 non-null  object
 24  Marka                     154030 non-null  object
 25  Model                     154030 non-null  object
 26  Mühərrik                  154030 non-null  object
 27  Qəzalı                    154030 non-null  object
 28  Rəng                      154030 non-null  object
 29  Sahiblər                  154030 non-null  object
 30  Sürətlər qutusu           154030 non-null  object
 31  Vəziyyəti                 154030 non-null  object
 32  Yeni                      154030 non-null  object
 33  Yerlərin sayı             154030 non-null  int64
 34  Yürüş                     154030 non-null  int64
 35  Ötürücü                   154030 non-null  object
 36  Şəhər                     154030 non-null  object
 37  year                      154030 non-null  int32
 38  month                     154030 non-null  int32
 39  day                       154030 non-null  int32
 40  mühərrik həcmi            154030 non-null  float64
 41  Yanacaq növü              154030 non-null  object
dtypes: datetime64[ns](2), float64(3), int32(3), int64(5), object(29)
memory usage: 48.8+ MB

In [26]:
df['Sahiblər'].unique()

array(['2', '0', '1', '3', '4 və daha çox'], dtype=object)

## Qruplar üzrə təsviri statistika (orta, median, standart sapma, paylanma forması)

In [27]:
df.describe()

,price_x,datetime_product,tarix,production_year,engine_displacement_num,kilometrage_num,views,Yerlərin sayı,Yürüş,year,month,day,mühərrik həcmi
count,154030.000000,154030,154030,154030.000000,154030.000000,1.540300e+05,154030.000000,154030.000000,1.540300e+05,154030.000000,154030.000000,154030.000000,154030.000000
mean,21733.826027,1900-01-01 15:56:24.983575040,2024-10-28 08:35:02.177498112,2004.287158,2.155237,2.129523e+05,607.990762,5.015283,2.130236e+05,2024.039174,9.917782,16.239278,2.088016
min,500.000000,1900-01-01 00:00:00,2024-09-13 00:00:00,0.000000,0.000000,0.000000e+00,17.000000,1.000000,0.000000e+00,2024.000000,1.000000,1.000000,0.000000
25%,10800.000000,1900-01-01 12:55:00,2024-09-30 00:00:00,2005.000000,1.600000,1.100000e+05,155.000000,5.000000,1.100000e+05,2024.000000,9.000000,9.000000,1.600000
50%,17800.000000,1900-01-01 16:16:00,2024-10-26 00:00:00,2011.000000,2.000000,1.970000e+05,249.000000,5.000000,1.970000e+05,2024.000000,10.000000,17.000000,2.000000
75%,27400.000000,1900-01-01 19:24:00,2024-11-21 00:00:00,2015.000000,2.400000,2.840000e+05,448.000000,5.000000,2.840000e+05,2024.000000,11.000000,24.000000,2.300000
max,940000.000000,1900-01-01 23:59:00,2025-01-05 00:00:00,2024.000000,120.000000,9.900025e+06,282819.000000,8.000000,9.900025e+06,2025.000000,12.000000,31.000000,9.700000
std,19228.309602,NaN,NaN,103.883566,1.225248,1.660570e+05,2568.211926,0.870446,1.659879e+05,0.194010,2.052301,8.824144,0.822201

In [28]:
group_statistika = df.groupby('Marka')['price_x'].agg(
    mean = 'mean',
    median = 'median',
    std = 'std'
).round(1)
group_statistika.head()

               mean   median      std
Marka
ATV          3508.3   3950.0   1691.3
Abarth      17400.0  18500.0   3501.8
Acura       17693.8  18575.0   4083.1
Alfa Romeo  54300.0  50100.0  34506.9
Aprilia     18699.5  21250.0   9359.0

In [29]:
paylanma = df.groupby('Marka')['price_x'].apply(lambda x: x.skew())

In [30]:
paylanma.head()

Marka
ATV          -0.814495
Abarth       -0.444105
Acura        -1.108845
Alfa Romeo    0.685219
Aprilia      -0.267631
Name: price_x, dtype: float64

In [31]:
group_statistika['skewness'] = paylanma
group_statistika.head()

               mean   median      std  skewness
Marka
ATV          3508.3   3950.0   1691.3 -0.814495
Abarth      17400.0  18500.0   3501.8 -0.444105
Acura       17693.8  18575.0   4083.1 -1.108845
Alfa Romeo  54300.0  50100.0  34506.9  0.685219
Aprilia     18699.5  21250.0   9359.0 -0.267631

## 2 biznes sualı üçün null/alternativ hipotezlərin formalaşdırılması

In [32]:
"""
Yanacaq növü (Benzin və Dizel) maşınların satış qiymətinə təsir edirmi?
Sıfır Hipotezi (H0):
Benzin və Dizel mühərrikli maşınların orta satış qiymətləri arasında statistik olaraq əhəmiyyətli fərq yoxdur
Alternativ Hipotez (H1):
Benzin və Dizel mühərrikli maşınların orta satış qiymətləri arasında statistik olaraq əhəmiyyətli fərq var
"""

'\nYanacaq növü (Benzin və Dizel) maşınların satış qiymətinə təsir edirmi?\nSıfır Hipotezi (H0):\nBenzin və Dizel mühərrikli maşınların orta satış qiymətləri arasında statistik olaraq əhəmiyyətli fərq yoxdur\nAlternativ Hipotez (H1):\nBenzin və Dizel mühərrikli maşınların orta satış qiymətləri arasında statistik olaraq əhəmiyyətli fərq var\n'

In [33]:
import scipy.stats as stats
benzin_prices = df[df['Yanacaq növü'] == 'Benzin']['price_x'].dropna()
dizel_prices = df[df['Yanacaq növü'] == 'Dizel']['price_x'].dropna()

t_stat, p_value = stats.ttest_ind(benzin_prices, dizel_prices, equal_var=False)
print(f"T-statistikası: {t_stat:.4f}")
print(f"p-value: {p_value:.4f}")
alpha = 0.05
if p_value < alpha:
    print("Result: H0 redd edilir (p < 0.05). Benzin və Dizel maşınların qiymetleri arasında statistik olaraq onemli ferq VAR.")
else:
    print("Result: H0 redd edile bilmir (p >= 0.05). Fərq statistik olaraq vacib DEYİL.")

T-statistikası: -41.4800
p-value: 0.0000
Result: H0 redd edilir (p < 0.05). Benzin və Dizel maşınların qiymetleri arasında statistik olaraq onemli ferq VAR.

In [34]:
groups = [group['price_x'].dropna() for name, group in df.groupby('Yanacaq növü')]
f_stat, p_value = stats.f_oneway(*groups)
print(f"F-statistikası: {f_stat:.4f}")
print(f"p-value: {p_value:.4f}")
alpha = 0.05
if p_value < alpha:
    print("Result: H0 rədd edilir (p < 0.05). Yanacaq növləri arasında qiymət fərqi statistik olaraq ƏHƏMİYYƏTLİDİR.")
else:
    print("Result: H0 redd edile bilmir (p >= 0.05). Yanacaq növleri arasında statistik olaraq vacib qiymet ferqi YOXDUR.")

F-statistikası: 651.4983
p-value: 0.0000
Result: H0 rədd edilir (p < 0.05). Yanacaq növləri arasında qiymət fərqi statistik olaraq ƏHƏMİYYƏTLİDİR.

## p-dəyərinin və etibar intervalının düzgün interpretasiyası (təkcə "p<0.05 = significant" deyil)
## Parametrik testdən əvvəl fərziyyələrin yoxlanması (normallıq, dispersiya bərabərliyi)

In [35]:
benzin = df[df['Yanacaq növü'] == 'Benzin']['price_x'].dropna()
dizel = df[df['Yanacaq növü'] == 'Dizel']['price_x'].dropna()
stat_benzin, p_benzin = stats.shapiro(benzin.sample(min(len(benzin), 5000)))
stat_dizel, p_dizel = stats.shapiro(dizel.sample(min(len(dizel), 5000)))
print("normalliq testi")
print(f"Benzin p-value: {p_benzin:.5f}")
print(f"Dizel p-value: {p_dizel:.5f}")

normalliq testi
Benzin p-value: 0.00000
Dizel p-value: 0.00000

In [36]:
if p_benzin < 0.05 and p_dizel < 0.05:
    print("Nəticə: Data normal paylanmır (p < 0.05)")
else:
    print("Nəticə: Data normal paylanmaya uyğundur.\n")

Nəticə: Data normal paylanmır (p < 0.05)

In [37]:
stat_lev, p_levene = stats.levene(benzin, dizel)
print(f"Levene p-value: {p_levene:.5f}")
if p_levene < 0.05:
    print("Netice: Dispersiyalar BƏRABƏR DEYİL (p < 0.05)")
else:
    print("Netice: Dispersiyalar bərabərdir (p >= 0.05).")

Levene p-value: 0.00000
Netice: Dispersiyalar BƏRABƏR DEYİL (p < 0.05)

## Statistik nəticəni biznes qərarına bağlayan yazılı nəticə

In [ ]:
"""
Benzin və dizel maşınlarının qiymət paylanmasında ciddi fərqliliklər olduğu üçün platformada vahid qiymətləndirmə modelindən istifadə etmək yanlış nəticələr verə bilər. 
Qiymət təyini və alqoritmlərdə hər mühərrik növü üçün ayrı-ayrı segmentasiya modelləri tətbiq edilməlidir.
Ayrıca, istifadəçilərə tövsiyə olunan qiymət filtrləri orta qiymətə deyil, median göstəricilərə əsaslanmalıdır. 
çünki lüks və ya həddən artıq baha maşınlar orta qiyməti süni şəkildə qaldıraraq alıcılar üçün real olmayan bazar mənzərəsi yaradır.
"""